### ISSUE TITLE
[Bug] Dark mode not available

### ISSUE THREAD

**Issue by kinisi-dlewiski** [creativetimofficial/ct-argon-dashboard-chakra-pro#3]
### Version
Latest version
### Reproduction link
http://localhost:3000
### Operating System
MacOS
### Device
Macbook
### Browser & Version
Chrome (latest)
### Steps to reproduce
Open the root folder in your code editor and search for any text including mode, dark mode, toggle mode, etc. Nothing can be found on how to set up or implement the dark theme.
### What is expected?
Documentation or at least some clear comments in the code on how to set up the dark theme and toggle between the two themes as demonstrated in the live preview. 
### What is actually happening?
In the demo of this template - nItps://demos.creative-
tim.com/argon-dashboard-chakra-
pro/#/admin/dashboard/default it shows both a dark mode and light mode. I downloaded the zip after paying for the bundle but there is nothing in the theme or in the code at large on modes, dark mode, toggle mode etc. Am I missing the code or instructions somewhere?

---

**Comment by simmmpleweb** [comment]
Hello, @kinisi-dlewiski ! Thanks for using our products. The version we are using has a fully function dark mode. Please check the gear icon button from the navbar where you can access the dark mode.
Regards, Vlad.

![Screenshot 2023-05-31 at 14 22 44](https://github.com/creativetimofficial/ct-argon-dashboard-chakra-pro/assets/90040741/f9064dbf-e42a-4a50-8ce5-4d3757c56e86)
![Screenshot 2023-05-31 at 14 22 30](https://github.com/creativetimofficial/ct-argon-dashboard-chakra-pro/assets/90040741/ef61c28c-eea5-4c9f-a7ab-ce768c01127f)
