### ISSUE TITLE
[Bug] After hot reloading add 1 iframe 

### ISSUE THREAD

**Issue by vinhnq-devblock** [creativetimofficial/ct-argon-dashboard-chakra-pro#4]
### Version
1.0.2
### Reproduction link
localhost
### Operating System
Window
### Device
PC
### Browser & Version
Chrome
### Steps to reproduce
1. Edit code
2. Hot Reloading
3. Showing 1 iframe in element tab in browser
![image](https://user-images.githubusercontent.com/88311053/231683088-833e2587-aa2a-4529-a71d-0f11b9d08862.png)

### What is expected?

Remove that iframe in element tab in browser
### What is actually happening?
Showing 1 iframe in element tab in browser

---

**Comment by vinhnq-devblock** [comment]
@timcreative  please check

**Comment by simmmpleweb** [comment]
Hello, @vinhnq-devblock ! Thanks for using our products ! It was fixed, in few minutes you will be able to get the fixed version!
Regards, Vlad.

**Comment by vinhnq-devblock** [comment]
Hello @simmmpleweb, I received the updated source code but I need to know what are your changes to fix the bug because I have used your template to change a lot of.

**Comment by vinhnq-devblock** [comment]
@timcreative  @simmmpleweb  please check and answer me pls

**Comment by simmmpleweb** [comment]
@vinhnq-devblock we added the following in package.json: 

"resolutions": {
    "react-error-overlay": "6.0.9"
  },
